### ISSUE TITLE
Query to get inventory count

### ISSUE THREAD

**Issue by itsbenweeks** [itsbenweeks/MET-CS579-project#1]
Let's calculate the sum of the quantity for every item in the inventory table.

**Comment by wilsonrey** [comment]
Do this look correct to you?

Select sum(i1."Quantity"+ i2."Quantity")
from INVENTORY i1 inner join INVENTORY i2
on (i2."Location" != i1."Location")
group by i1."ItemSKU";

**Comment by wilsonrey** [comment]
-- Query orders place by customer--
Select "OrderID", ITEM."ItemSKU", ITEM."ItemName", CUSTOMER."CustomerID"
from "ORDER", CUSTOMER, ITEM
where "ORDER"."CustomerID" = CUSTOMER."CustomerID" and "ORDER"."ItemSKU" = ITEM."ItemSKU" and CUSTOMER."CustomerID" = &CustomerID ;

**Comment by itsbenweeks** [comment]
Almost, but I don't think we need the join for the differing locations. This should work instead:

```sql
select INVENTORY."ItemSKU", sum(INVENTORY."Quantity")
from INVENTORY 
group by INVENTORY."ItemSKU";
```

**Comment by itsbenweeks** [comment]
Got the 👍 from Wilson.
